apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
data:
  log-format: |
    '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent '
    '"$http_referer" "$http_user_agent" "$request_time" "$upstream_response_time" '
    '"$upstream_cache_status" $host';
  access-log-off: "false"